services:
  data-database:
    image: mongo:8.0-rc
    ports:
      - "27017:27017"
    networks:
      - backend


  # content-database:
  #   image: 
  #   ports:
  #     - ""
  #   networks:
  #     - backend

networks:
  frontend: {}
  backend: {}